{
  "DATA_PATH": "./datasets",
  "RESULTS_PATH": "./Results",
  "SPLITS_PATH": "./datasets/splits",
  "TESTS_PATH": "./Tests",
  "LOCAL_TRACKING_PATH": "./Tracking", 
  
  # Which tracker to use: Local, WandB, None
  "tracker": "WandB",
  "project": "BasicGNNProject"
}